### ISSUE TITLE
Throwing error in phoenix framework 1.3

### ISSUE THREAD

**Issue by karthikeyan234** [bryanjos/geo_postgis#1]
I created a sample phoenix 1.3 project using 

`sudo mix phx.new Server --app locationsearch --no-html --no-brunch

Installed this library as dependency 

```
mix.exs

  defp deps do
    [
      {:phoenix, "~> 1.3.0"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:postgrex, ">= 0.0.0"},
      {:gettext, "~> 0.11"},
      {:cowboy, "~> 1.0"},
      {:geo_postgis, "~> 1.0"}
    ]
  end
```
```

dev,exs

# Configure your database
config :locationsearch, Locationsearch.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "postgres",
  password: "123456",
  database: "locationsearch_dev",
  hostname: "localhost",
  pool_size: 10,
  extensions: [{Geo.PostGIS.Extension, library: Geo}]
```
`
In My Priv Folder

File 1: 
```
defmodule Locationsearch.Repo.Migrations.EnablePostgis do
  use Ecto.Migration

  def change do

  end

  def up do
    execute "CREATE EXTENSION IF NOT EXISTS postgis"
  end

  def down do
    execute "DROP EXTENSION IF EXISTS postgis"
  end

end
```

File 2 :`
```

defmodule Locationsearch.Repo.Migrations.CreateShipData do
  use Ecto.Migration

  def up do
    create table(:test) do
      add :name,     :string
      add :geom,     :geometry
    end
  end

  def down do
    drop table(:test)
  end
  
end
```

Dont know where to put this code

```
Postgrex.Types.define(Locationsearch.PostgresTypes,
              [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
              json: Poison)
```

When i run 
`mix ecto.migrate`

I am getting lots of errors tried different solutons but nothing works

Can you tell me where i am going wrong.

Do you have any idea to build a example phoenix1.3 app with this library if so it would be very helpful for many of us.

Thanks.Your help is much appreciated

**Comment by karthikeyan234** [comment]
Issue Solved

config/config.exs

use Mix.Config

```
config :test, ecto_repos: [Test.Repo]

config :test, Test.Repo,
  types: Test.PostgrexTypes

import_config "#{Mix.env}.exs"
```

lib/test/postgrex_types.ex

Postgrex.Types.define(Test.PostgrexTypes,
  [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
  json: Poison)

But it's an umbrella app. I don't think it would be much different in a phoenix app. There I would also place postgrex_types.ex somewhere in lib.

Source : https://elixirforum.com/t/where-to-call-postgrex-types-define-in-phoenix-ecto-project/4810/2

**Comment by dongli** [comment]
I have faced with the similar errors:

```
(ArgumentError) invalid or unknown type Geo.Point for field
```
