### ISSUE TITLE
Broken link on `README.md`

### ISSUE THREAD

**Issue by brianmay** [bryanjos/geo_postgis#16]
Hello,

I noticed there is a broken link in `README.md` to https://hexdocs.pm/ecto/Ecto.Adapters.Postgres.html#module-extensions

Also wondering if this project is compatible with Ecto 3 or not. Some clarification in the documentation would be really useful. Looking at #15 I note failures, however not entirely convinced if this is an Ecto 3 compatible issue or not.

Thanks

**Comment by bryanjos** [comment]
Closed with #35
