### ISSUE TITLE
Is the README's example point (30, -90) in Antarctica?

### ISSUE THREAD

**Issue by tombh** [bryanjos/geo_postgis#43]
Please correct me if I'm wrong, but if Elixir's `Geo.Point{coordinates: {x, y}, srid: 4326}` builds a Postgis `POINT(x, y)`, then `%Geo.Point{coordinates: {30, -90}, srid: 4326}` is somewhere in Antarctica. Reversing the coords instead places the point to a more relevant location in New Orleans, America.

I mention this because there aren't actually any docs that formally state the order of the axis, so the easiest thing for me was to quickly google the example point and decipher the order based on the relevance of Antarctica versus New Orleans. Of course that's a pretty unreliable method on my part! In hindsight it seems obvious that `Geo.Point` would just defer to Postgis's native ordering, so if I'm right would it be good to note that in the README and reverse the example point?

**Comment by bryanjos** [comment]
Haha I think you are right

**Comment by tombh** [comment]
But the README is still the same?? You haven't reversed the point, or mentioned that [30, 90] is in Antarctica??
