### ISSUE TITLE
type `geometry` can not be handled by the types module Postgrex.DefaultTypes

### ISSUE THREAD

**Issue by hammadurrahman** [bryanjos/geo_postgis#54]
Added in .ex file.
```
Postgrex.Types.define(
  Core.PostgresTypes,
  [Geo.PostGIS.Extension] ++ Ecto.Adapters.Postgres.extensions(),
  json: Jason
)
```
Model: i have this field
    field :location, Geo.PostGIS.Geometry

Migrations:
      add :location, :geometry

Postgis extension created:
CREATE EXTENSION IF NOT EXISTS postgis;

config:
  types: Core.PostgresTypes,

On my mac its working fine. but On live server(ubuntu) not working.
On mac:
postgis version: 2.4.4
postgresql version: 11.5

Live server:
postgis version: 2.5.2
postgresql version: 11.5

can anyone let me know what is missing, why it is not working on live server.

**Comment by hammadurrahman** [comment]
resolved

**Comment by mrcdll** [comment]
What was the resolution @hammadurrahman ?
