### ISSUE TITLE
st_distance_in_meters(g.geo_point(), ^geo_point) is not a valid query expression.

### ISSUE THREAD

**Issue by philippneugebauer** [bryanjos/geo_postgis#7]
I'm getting the following error message for calling `st_distance_in_meters()`
```elixir
** (Ecto.Query.CompileError) `st_distance_in_meters(g.geo_point(), ^geo_point)` is not a valid query expression.
```
with the following snippet:
```elixir
Repo.all from u in User,
  select: %{u | distance: st_distance_in_meters(g.geo_point, ^geo_point)}
```
While the snippet above fails, it works like a charme for `st_distance`.

```elixir
Repo.all from u in User,
  select: %{u | distance: st_distance(g.geo_point, ^geo_point)}
```

As much as I understood the code, both functions take the same input and therefore it should work. I don't really understand why `g.geo_point` is enhanced to a function in the first case, but is taken as a variable in the second call.

**Comment by tonyc** [comment]
Try removing the `()` in your first query after `g.geo_point` perhaps?

**Comment by philippneugebauer** [comment]
I figured out the problem: `st_distance_in_meters` is included in the repository, but not part of the current hex release. So you need to change your dependency to github to utilize this function. Unfortunately, this does not help you, because there are some types in the function, resulting in the following error:

```elixir
** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 42883 (undefined_function): function st_dwithin(geography, geography) does not exist
        (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
        (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
```

**Comment by vasspilka** [comment]
Hmmm yes seems to be added after the 2.0 release, you can always use `fragment("expr")` from Ecto to do custom stuff
